name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    name: "CI (Node ${{ matrix.node }})"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20, 22, 24]

    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"
      - run: pnpm install

      - run: pnpm lint
      - run: pnpm test
      - run: pnpm build

      - run: pnpm test:e2e:install
      - run: pnpm test:e2e
